// File generated by FlutterFire CLI.
// Updated with actual Firebase configuration from google-services.json

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import firebase_options.dart';
/// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIza5yCmB5P6sA5V5RJwJqJY8-Mg6Gq8h5PbbbMM',
    appId: '1:1087655198384:web:PLACEHOLDER',
    messagingSenderId: '1087655198384',
    projectId: 'kharcha-book-m8g8bs',
    authDomain: 'kharcha-book-m8g8bs.firebaseapp.com',
    storageBucket: 'kharcha-book-m8g8bs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIza5yCmB5P6sA5V5RJwJqJY8-Mg6Gq8h5PbbbMM',
    appId: '1:1087655198384:android:b2dffc2cc252fc4eadc575',
    messagingSenderId: '1087655198384',
    projectId: 'kharcha-book-m8g8bs',
    storageBucket: 'kharcha-book-m8g8bs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIza5yCmB5P6sA5V5RJwJqJY8-Mg6Gq8h5PbbbMM',
    appId: '1:1087655198384:ios:PLACEHOLDER',
    messagingSenderId: '1087655198384',
    projectId: 'kharcha-book-m8g8bs',
    storageBucket: 'kharcha-book-m8g8bs.firebasestorage.app',
    iosBundleId: 'com.mycompany.kharchabook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIza5yCmB5P6sA5V5RJwJqJY8-Mg6Gq8h5PbbbMM',
    appId: '1:1087655198384:ios:PLACEHOLDER',
    messagingSenderId: '1087655198384',
    projectId: 'kharcha-book-m8g8bs',
    storageBucket: 'kharcha-book-m8g8bs.firebasestorage.app',
    iosBundleId: 'com.mycompany.kharchabook',
  );
}
